### ISSUE TITLE
Cannot find dict.source.txt and dict.target.txr

### ISSUE THREAD

**Issue by RibinMathewChalumattu** [uhh-lt/multi-summ-german#1]
Hello,

I wanted to run the fine-tuned bart model using the provided checkpoint. However, when I call BARTModel.from_pretrained, I get an error message that dict.source.txt and dict.target.txt are not found. Where can I find these files? Could you provide a more detailed instruction on how to make inferences with fine tuned model?

Best,

Ribin

**Comment by timojohlo** [comment]
Hi Ribin,

The inference should work like described [here](https://github.com/pytorch/fairseq/blob/main/examples/bart/README.summarization.md). We have also uploaded the dict.source.txt and dict.target.txt file [here](http://ltdata1.informatik.uni-hamburg.de/nodalida-2021-timo/), so now you should be able to test the model.

Best regards,
Timo

**Comment by RibinMathewChalumattu** [comment]
Hi Timo, 

Thank you very much for the information. I'm a research engineer working at ETH Zurich on Multi-document summarization for german news articles. I have two more questions: 

1. Which pretrained BART model was used, to fine-tune on the auto-hMDS dataset?
2. Is it possible to share auto-hMDS dataset with us? On the dataset [website](https://github.com/AIPHES/auto-hMDS#obtaining-the-full-corpus), it was mentioned that some of the inlcuded webpages in the corpus are no longer available. I was wondering if you had already stored the full dataset somewhere.

Best,
Ribin

**Comment by timojohlo** [comment]
Hi Ribin,

Cool to see that you are also working on this topic. 

Regarding your questions:

> Which pretrained BART model was used, to fine-tune on the auto-hMDS dataset?

We used the pre-trained bart-large model with 12 encoder and decoder layers provided through the fairseq library. See [here](https://github.com/pytorch/fairseq/tree/main/examples/bart). 

> Is it possible to share auto-hMDS dataset with us? On the dataset [website](https://github.com/AIPHES/auto-hMDS#obtaining-the-full-corpus), it was mentioned that some of the inlcuded webpages in the corpus are no longer available. I was wondering if you had already stored the full dataset somewhere.

We do not longer have access to the dataset and as far as I know the dataset is not publicly available due to copyright restrictions. But you should try to contact the authors (e.g. M. Zopf) of the corresponding paper. They can probably provide you with the full dataset. 

Best regards,
Timo

**Comment by RibinMathewChalumattu** [comment]
Hey Timo,

I have a couple more follow up questions:

1. Was the BART pre-trained on multilingual data, in order to finetune on the german auto-hMDS dataset? I could not find information about the language BART was pre-trained on.
2. Why was the BART-DYNE-1/5(Hokamp et al.) only used for English and not for german? I'm referring to Tables 2 and 3 from your paper. 
Best,

Ribin

**Comment by timojohlo** [comment]
Hi @RibinMTC 

regarding your questions:
> 1. Was the BART pre-trained on multilingual data, in order to finetune on the german auto-hMDS dataset? I could not find information about the language BART was pre-trained on.

You are right. In the paper they did not state what data they used for pre-training. That is why we were in exchange with Mike Lewis, one of the authors of the BART paper. He said that they used a couple of different sources of data to train BART, but it was primarily English Wikipedia and English news scraped from the Common Crawl.

> 2. Why was the BART-DYNE-1/5(Hokamp et al.) only used for English and not for german? I'm referring to Tables 2 and 3 from your paper.

We did not apply the model BART-DYNE-1/5 on our German language dataset due to time constraints. So table 2 only shows how the baseline models (including BART-DYNE-1/5) perform on the Multi-News dataset compared to BART pre-trained and BART fine-tuned. But it might be worth a try. 

Good luck with your research!

Best regards,
Timo

**Comment by timojohlo** [comment]
I will close this issue. If you have any further questions feel free to open a new issue or write me a mail.
